### ISSUE TITLE
проверка может ломать блоки на спавне и тп

### ISSUE THREAD

**Issue by Medved0546** [Kepchyk1101/UltimateCheatCheck#1]
когда проверка начинается то под подореваемым устанавливается блок бедрока который ломает основной блок так вот основной блок то возращается но то что на нём росло нет (цветы и тп на спавне хелперы если захотят смогут так разломать мб) и много чего ещё неприятного наверн

так вот добавь функцию для отключения установки этого блока

ps щя проверил ещё с плагином bairdrop так этот блок аирдроп ломает ещё
![javaw_uzoeGySvnC](https://github.com/Kepchyk1101/UltimateCheatCheck/assets/140727790/d06ad58c-8135-4a61-a7e5-b7ad65d637ba)
![javaw_DRzIFQMrAL](https://github.com/Kepchyk1101/UltimateCheatCheck/assets/140727790/c28b2ed2-e8f9-4743-b554-672c5a11e9ea)

**Comment by Kepchyk1101** [comment]
Привет, я знал о этой проблеме, но посчитал что она слишком маловероятна чтобы думать как её предотвратить, постараюсь решить в ближайшее время. Благодарю за отзыв

**Comment by Kepchyk1101** [comment]
> когда проверка начинается то под подореваемым устанавливается блок бедрока который ломает основной блок так вот основной блок то возращается но то что на нём росло нет (цветы и тп на спавне хелперы если захотят смогут так разломать мб) и много чего ещё неприятного наверн
> 
> 
> 
> так вот добавь функцию для отключения установки этого блока
> 
> 
> 
> ps щя проверил ещё с плагином bairdrop так этот блок аирдроп ломает ещё
> 
> ![javaw_uzoeGySvnC](https://github.com/Kepchyk1101/UltimateCheatCheck/assets/140727790/d06ad58c-8135-4a61-a7e5-b7ad65d637ba)
> 
> ![javaw_DRzIFQMrAL](https://github.com/Kepchyk1101/UltimateCheatCheck/assets/140727790/c28b2ed2-e8f9-4743-b554-672c5a11e9ea)
> 
> 

Чёто я затянул наверное..
Я решил удалить пока-что эту функцию, посмотрим че будет
Если актуально еще - на spigotmc 1.4.0 версию с фиксом
:)
